services:
  - type: web
    name: bitebox-canteen
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 bitebox.backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
